version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sql_query_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: firozdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: sql_query_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/firozdb
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
